title: AI Conference Deadlines
description: Countdowns to top CV/ML conference deadlines
author: Sayak Mukherjee

domain: "https://SayakMukherjee.github.io/"
baseurl: "/ai-deadlines"

twitter_hashtag: _sayak_m_
github_username: SayakMukherjee
github_repo: ai-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
