title: AI Conference Deadlines
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Abhishek Das

domain: "https://SayakMukherjee.github.io/"
baseurl: "/ai-deadlines"

twitter_hashtag: machinelearning
github_username: SayakMukherjee
github_repo: ai-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
